todo_project/accounts_app/urls.py
from django.urls import path
from .import views

app_name = "accounts_app"

urlpatterns = [
    path("", views.login, name="login"),
    path("sign-up", views.sign_up, name="sign_up"),
    path("logout", views.logout, name="logout")
]

todo_project/todo_app/urls.py
from django.urls import path
from .import views

app_name = "todo_app"

urlpatterns = [
    path("", views.todos, name="todos"),
    path("delete/<int:todo_id>", views.delete_todo, name="delete"),
    path('update/<int:todo_id>', views.update_todo, name="update")
]

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts_app.urls')),
    path('todos/', include('todo_app.urls'))
]

todo_project/todo_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Todo(models.Model):
    """
    Represents a todo entity
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    completed = models.BooleanField(default=False)

    def update_completed(self):
        """
        Updates the completed property to be the opposite
        """
        self.completed = not self.completed

todo_project/accounts_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.contrib.auth.models import User
# Create your views here.


def login(request):
    """
    Handles login get and post requests
    """
    context = {
        'title': 'Login'
    }

    if request.method == "POST":
        user = authenticate(
            request,
            username=request.POST["username"],
            password=request.POST["password"]
        )

        if user:
            dj_login(request, user)
            return redirect("todo_app:todos")

    return render(request, 'accounts_app/login.html', context)


def sign_up(request):
    """
    Handles sign up get and post requests
    """
    context = {
        'title': 'Sign up'
    }

    if request.method == "POST":
        if not User.objects.filter(username=request.POST["username"]):
            User.objects.create_user(
                username=request.POST["username"],
                password=request.POST["password"],
            )
            return redirect("accounts_app:login")

    return render(request, 'accounts_app/sign-up.html', context)


def logout(request):
    """
    Handles logout get request
    """
    dj_logout(request)
    return redirect('accounts_app:login')

todo_project/todo_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Todo
# Create your views here.


@login_required
def todos(request):
    """
    Rendering users todo on get and creates one on post
    """
    context = {
        'title': 'Todo List'
    }

    if request.method == "POST":
        todo = Todo(
            user=request.user,
            description=request.POST["description"]
        )
        todo.save()

    context['todos'] = Todo.objects.all().filter(user=request.user)
    return render(request, 'todo_app/todos.html', context)


@login_required
def delete_todo(request, todo_id):
    """
    Deletes a todo
    """
    Todo.objects.filter(id=todo_id).delete()
    return redirect('todo_app:todos')


@login_required
def update_todo(request, todo_id):
    """
    Updates a todo
    """
    todo = Todo.objects.get(id=todo_id)
    todo.completed = not todo.completed
    todo.save()
    return redirect('todo_app:todos')

todo_project/accounts_app/templates/accounts_app/login.html
{% extends 'base.html' %} 
{% block content %}
<div class="max-w-2xl mx-auto bg-gray-200 p-10 rounded shadow">
    <h1 class="mb-4 text-2xl font-semibold">Login</h1>
    <form method="POST" action="" class="flex flex-col">
        {% csrf_token %}
        <input type="text" placeholder="Username" name="username" class="mb-4 p-4 rounded" />
        <input type="password" placeholder="Password" name="password" class="mb-4 p-4 rounded" />
        <button class="bg-green-400 text-white py-4 rounded">Login</button>
    </form>
</div>
{% endblock %}

todo_project/accounts_app/templates/accounts_app/sign-up.html
{% extends 'base.html' %} 
{% block content %}
<div class="max-w-2xl mx-auto bg-gray-200 p-10 rounded shadow">
    <h1 class="mb-4 text-2xl font-semibold">Sign up</h1>
    <form method="POST" action="" class="flex flex-col">
        {% csrf_token %}
        <input type="text" placeholder="Username" name="username" class="mb-4 p-4 rounded" />
        <input type="password" placeholder="Password" name="password" class="mb-4 p-4 rounded" />
        <button class="bg-green-400 text-white py-4 rounded">Sign up</button>
    </form>
</div>
{% endblock %}

todo_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>{{title}}</title>
		<link
			href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
			rel="stylesheet"
		/>
		<link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
			integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
			crossorigin="anonymous"
		/>
	</head>
	<body>
		<nav
			class="
				bg-blue-600
				text-white
				px-12
				py-8
				shadow-lg
				flex
				justify-between
				mb-8
			"
		>
			<a href="">Todo or not todo</a>
			<div>
				{% if user.is_authenticated %}
				<a href="{% url 'accounts_app:logout' %}">Logout</a>
				{% else %}
				<a href="{% url 'accounts_app:login' %}" class="mr-10">Login</a>
				<a href="{% url 'accounts_app:sign_up' %}">Sign up</a>
				{% endif %}
			</div>
		</nav>
		<main class="container p-4 mx-auto">
			{% block content %} {% endblock %}
		</main>
	</body>
</html>

todo_project/todo_app/templates/todo_app/todos.html
{% extends 'base.html' %} 
{% block content %}
<div class="max-w-4xl mx-auto">
    <div>
        <form class="flex flex-col bg-gray-200 p-10 rounded shadow-md" method="POST">
            {% csrf_token %}
            <h1 class="mb-4 text-2xl font-semibold">Create Todo</h1>
            <input type="text" placeholder="Description" class="p-4 rounded" name="description" />
            <button class="py-4 bg-green-400 text-white mt-4 rounded">Create</button>
        </form>
    </div>

    {% for todo in todos %}
        <div class="bg-gray-200 rounded shadow-md p-10 mt-10">
            <div class="flex justify-between items-center">
                <h3 class="text-xl font-semibold">{{todo.description}}</h3>
                <form method="POST" action="{% url 'todo_app:delete' todo_id=todo.id %}">
                    {% csrf_token %}
                    <button><i class="far fa-trash-alt"></i></button>
                </form>
            </div>
            <form action="{% url 'todo_app:update' todo_id=todo.id %}">
                {% if todo.completed %}
                <button class="bg-red-400 text-white py-2 px-4 rounded mt-4">
                    Undo
                </button>
                {% else %}
                <button class="bg-green-400 text-white py-2 px-4 rounded mt-4">
                    Complete
                </button>
                {% endif %}
            </form>
        </div>
    {% endfor %}
</div>
{% endblock %}